spring:
  application:
    name: pet_clinic_jpa

  liquibase:
    change-log: db/changelog/changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/pet_clinic
    username: postgres
    password: q1w2e3r4

  data:
    redis:
      host: localhost
      port: 6379
      password: q1w2e3r4
      lettuce:
        pool:
          max-active: 6
          max-idle: 6
          min-idle: 2
          enabled: true
      client-name: ${spring.application.name}

  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false
        query:
          in_clause_parameter_padding: true

server:
  port: 8099
  servlet:
    context-path: /api/clinic/v1

management:
  server:
    port: 8901
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true